backend:
  name: github
  repo: "kirubaisathiyam-dev/kirubaisathiyam"
  branch: "main"
  site_domain: "fb8ea160-3f8b-4243-8b4e-981d1679dc74"
  auth_type: implicit
  app_id: Ov23liUveATlqLvpISjv

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "articles"
    label: "Articles"
    folder: "content/articles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}{{minute}}{{second}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false }
      - { label: "Author", name: "author", widget: "string" }
      - label: "Tags"
        name: "tags"
        widget: "list"
        required: true
        min: 1
        field: { label: "Tag", name: "tag", widget: "string" }
      - label: "Keywords"
        name: "keywords"
        widget: "list"
        required: true
        min: 1
        field: { label: "Keyword", name: "keyword", widget: "string" }
      - { label: "Summary", name: "summary", widget: "text", required: false }
      - { label: "Cover Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
